# AppVeyor CI configuration file https://www.appveyor.com/
#
# SPDX-FileCopyrightText: Placed into the public domain by Dan Fandrich
# SPDX-License-Identifier: CC0-1.0

image: Visual Studio 2022
environment:
  CYGWIN_MIRROR: https://cygwin.mirror.constant.com
  matrix:
  - CONFIG: cygwin64
  - CONFIG: msys2

install:
- cmd: if [%CONFIG%]==[cygwin64] (
    C:\cygwin64\setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -s "%CYGWIN_MIRROR%" -P libiconv-devel )
- cmd: if [%CONFIG%]==[msys2] (
    set "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%" )
- cmd: if [%CONFIG%]==[msys2] (
    bash -lc "pacman -S --noconfirm --noprogressbar --needed libtool mingw-w64-x86_64-{autotools,libtool,gettext,libiconv}" )

build_script:
- cmd: if [%CONFIG%]==[cygwin64] (
    C:\%CONFIG%\bin\bash -e -l -c "cd $APPVEYOR_BUILD_FOLDER && autoreconf -sif && ./configure --prefix=$HOME --disable-dependency-tracking && make V=1 LDFLAGS='-lintl' && make V=1 install" )
- cmd: if [%CONFIG%]==[msys2] (
    bash -lc "set -x; cd $APPVEYOR_BUILD_FOLDER && gettext_datadir=/mingw64/share/gettext autoreconf -sivf && ./configure --prefix=$HOME/install --disable-dependency-tracking && make V=1 && make V=1 install" )

test_script:
- cmd: if [%CONFIG%]==[cygwin64] (
    C:\%CONFIG%\bin\bash -e -l -c "cd $APPVEYOR_BUILD_FOLDER && make V=1 check" )
- cmd: if [%CONFIG%]==[msys2] (
    bash -lc "cd $APPVEYOR_BUILD_FOLDER && make V=1 check" )

branches:
  only:
    - master
    - /\/ci$/

skip_commits:
  files:
    - '.cirrus.yml'
    - '.github/**/*'
    - '.reuse/*'
    - 'LICENSES/*'
